### ISSUE TITLE
New moderation command(s) crash Glass Live

### ISSUE THREAD

**Issue by ShockFromBL** [BlocklandGlass/Glass-Live#14]
`/getpermid` crashed the server when checking an offline user who was confirmed to have a service ban in effect, but did not initially crash the server when checking an innocent user.

The following Glass Live commands should be checked for errors:

- [x] `/getperm`
- [x] `/getpermid`
- [x] `/resetperm`
- [x] `/resetpermid`
- [x] `/forceicon`
- [x] `/forceiconid`

**Comment by nightkr** [comment]
That sounds like a bigger problem.., especially in a language as error-prone as JS. "Be really careful" doesn't really work when humans are involved. :P

You probably want to put a global exception handler around each connection, so that errors handling one user only brings down their own connection (and not the whole service).

**Comment by dpendic** [comment]
Added parameter number validation (7037cdd), passing command without enough arguments was causing a crash.

There's a high-level try/catch when handling any input from connections, has been there since day one. Not sure what is causing exceptions to get through.

**Comment by ShockFromBL** [comment]
Commands fixed in e02538165a50cb5426900c2a8f1392883d3b1fe1
